name: "PackerBuild"

on:
  workflow_dispatch:
    inputs:
      description: Base Image Build Version
      #type: string
      required: true
      default: 1.0.0

jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y packer

      - name: Determine Environment
        id: set-env
        run: |
          # Get branch name from either push event or workflow_dispatch
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            BRANCH_NAME="${{ github.event.inputs.branch }}"
          else
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
          fi

          echo "Detected branch: $BRANCH_NAME"

          case "$BRANCH_NAME" in
            "dev") ENV_FILE="dev.pkrvars.hcl" ;;
            "staging") ENV_FILE="staging.pkrvars.hcl" ;;
            "prod") ENV_FILE="prod.pkrvars.hcl" ;;
            *) echo "Unknown branch! Exiting." && exit 1 ;;
          esac

          echo "ENV_FILE=$ENV_FILE" >> $GITHUB_ENV

      - name: Run Packer Build
        run: |
          packer init .
          packer build -var-file=${{ env.ENV_FILE }} template.pkr.hcl
  